FROM alpine:3.12.3
ENTRYPOINT ["/bin/echo", "Hello World!"]

# Alpine es un sistema operativo basado en linux que se destaca por ser muy liviano
# https://hub.docker.com/_/alpine
#
# Aunque tambien se pudo haber utilizado CMD dicho comando es recomendado solo cuando se desea
# un cierto grado de interacción con el usuario mediante consola, por lo que se optó por ENTRYPOINT
# Estos detalles se explicaran mas adelante.