FROM nginx
COPY index.html /usr/share/nginx/html

# nginx es el servidor web más utilizado junto a Apache
# https://hub.docker.com/_/nginx
#
# Copiamos la pagina html que hemos creado dentro del contenedor (en el directorio que nginx indica)